// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ProjectGram.Models.Data;
using System;

namespace ProjectGram.Migrations
{
    [DbContext(typeof(GramDbContext))]
    [Migration("20190420022555_fotoIdRemovedCommentLikes")]
    partial class fotoIdRemovedCommentLikes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectGram.Models.Archive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FotoId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("FotoId");

                    b.HasIndex("UserId");

                    b.ToTable("Archives");
                });

            modelBuilder.Entity("ProjectGram.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created_at");

                    b.Property<int?>("FotoId");

                    b.Property<string>("Text");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("FotoId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("ProjectGram.Models.CommentLikes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CommentId");

                    b.Property<int?>("CommentLikeId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("CommentLikeId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentLikes");
                });

            modelBuilder.Entity("ProjectGram.Models.Followed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FollowsId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("FollowsId")
                        .IsUnique()
                        .HasFilter("[FollowsId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Followed");
                });

            modelBuilder.Entity("ProjectGram.Models.Follows", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("ProjectGram.Models.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CommentLikesId");

                    b.Property<string>("Descripcion")
                        .IsRequired();

                    b.Property<DateTime>("Fecha");

                    b.Property<string>("Ruta");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommentLikesId");

                    b.HasIndex("UserId");

                    b.ToTable("Foto");
                });

            modelBuilder.Entity("ProjectGram.Models.Likes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FotoId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("FotoId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("ProjectGram.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido")
                        .IsRequired();

                    b.Property<string>("Avatar");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<DateTime>("FNacimiento");

                    b.Property<string>("NickName")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Sexo");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ProjectGram.Models.Archive", b =>
                {
                    b.HasOne("ProjectGram.Models.Foto", "Foto")
                        .WithMany("Archives")
                        .HasForeignKey("FotoId");

                    b.HasOne("ProjectGram.Models.User", "User")
                        .WithMany("Archives")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ProjectGram.Models.Comment", b =>
                {
                    b.HasOne("ProjectGram.Models.Foto", "Foto")
                        .WithMany("Comments")
                        .HasForeignKey("FotoId");

                    b.HasOne("ProjectGram.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ProjectGram.Models.CommentLikes", b =>
                {
                    b.HasOne("ProjectGram.Models.Comment", "Comment")
                        .WithMany("CommentLikes")
                        .HasForeignKey("CommentId");

                    b.HasOne("ProjectGram.Models.CommentLikes", "CommentLike")
                        .WithMany()
                        .HasForeignKey("CommentLikeId");

                    b.HasOne("ProjectGram.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ProjectGram.Models.Followed", b =>
                {
                    b.HasOne("ProjectGram.Models.Follows", "Follows")
                        .WithOne("Followed")
                        .HasForeignKey("ProjectGram.Models.Followed", "FollowsId");

                    b.HasOne("ProjectGram.Models.User", "User")
                        .WithMany("FollowedList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProjectGram.Models.Follows", b =>
                {
                    b.HasOne("ProjectGram.Models.User", "User")
                        .WithMany("Follows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProjectGram.Models.Foto", b =>
                {
                    b.HasOne("ProjectGram.Models.CommentLikes", "CommentLikes")
                        .WithMany()
                        .HasForeignKey("CommentLikesId");

                    b.HasOne("ProjectGram.Models.User", "User")
                        .WithMany("Foto")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProjectGram.Models.Likes", b =>
                {
                    b.HasOne("ProjectGram.Models.Foto", "Foto")
                        .WithMany("Likes")
                        .HasForeignKey("FotoId");

                    b.HasOne("ProjectGram.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
